// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qitoncfoeoncazrjxycq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpdG9uY2ZvZW9uY2F6cmp4eWNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODEyMDUsImV4cCI6MjA2NjM1NzIwNX0.ZCNqC_c0eACGRT5xdCNc5eD0FhLzxy-uLqU11ZdnEEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);